ALTER TABLE borsa_data 
ADD COLUMN IF NOT EXISTS low TEXT,
ADD COLUMN IF NOT EXISTS high TEXT,
ADD COLUMN IF NOT EXISTS aof TEXT,
ADD COLUMN IF NOT EXISTS volume_lot TEXT,
ADD COLUMN IF NOT EXISTS volume_tl TEXT;
