create table if not exists public.market_snapshots (
    id bigint generated by default as identity primary key,
    fetched_at timestamptz not null,
    source text not null default 'www.doviz.com',
    usd_try numeric,
    usd_try_change text,
    usd_status text,
    eur_try numeric,
    eur_try_change text,
    eur_status text,
    gram_gold_try numeric,
    gram_gold_change text,
    gold_status text,
    bist100 numeric,
    bist100_change text,
    bist_status text,
    bitcoin numeric,
    bitcoin_change text,
    btc_status text,
    brent numeric,
    brent_change text,
    brent_status text,
    created_at timestamptz not null default now()
);

create index if not exists market_snapshots_fetched_at_idx
    on public.market_snapshots (fetched_at desc);

alter table public.market_snapshots enable row level security;

drop policy if exists "market_snapshots_public_read" on public.market_snapshots;
create policy "market_snapshots_public_read"
    on public.market_snapshots
    for select
    using (true);
